"use client";

import { useState } from "react";
import { adminFetch } from "@/lib/admin-fetch";
import type { AIGenerateTask } from "@/lib/ai/types";

export function AIGeneratePanel({
  task,
  label,
  prompt,
  context,
  buttonLabel = "Generate with AI",
}: {
  task: AIGenerateTask;
  label: string;
  prompt: string;
  context?: Record<string, unknown>;
  buttonLabel?: string;
}) {
  const [open, setOpen] = useState(false);
  const [result, setResult] = useState("");
  const [provider, setProvider] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function generate() {
    setLoading(true);
    setOpen(true);
    setResult("");
    setError("");
    setProvider("");
    try {
      const res = await adminFetch("/api/admin/ai/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ task, prompt, context }),
      });
      const data = (await res.json().catch(() => ({}))) as {
        content?: string;
        provider?: string;
        ok?: boolean;
        reason?: string;
        error?: string;
      };

      if (!res.ok || data.ok === false || !data.content) {
        setError(
          data.reason ||
            data.error ||
            (res.status === 504
              ? "The model took too long to respond. Try again — the request timed out."
              : `Generation failed (HTTP ${res.status}).`)
        );
      } else {
        setResult(data.content);
        setProvider(data.provider ?? "");
      }
    } catch {
      setError("Could not reach the generation service. Check your connection and try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mt-4 border-t border-stone/20 pt-4">
      <button
        type="button"
        onClick={generate}
        disabled={loading}
        className="text-xs tracking-[0.12em] text-accent uppercase hover:text-cream disabled:opacity-50"
      >
        ✦ {loading ? "Generating…" : buttonLabel}
      </button>

      {open && (
        <div className="mt-3 rounded-lg border border-stone/25 bg-ink/50 p-4">
          <p className="mb-2 text-[0.65rem] tracking-[0.14em] text-muted uppercase">{label} — DRAFT</p>
          {loading ? (
            <p className="text-sm text-fog animate-pulse">ÉLEVÉ AI is writing…</p>
          ) : error ? (
            <div className="rounded-md border border-red-500/30 bg-red-500/5 p-3">
              <p className="text-[0.65rem] uppercase tracking-[0.12em] text-red-400">Generation failed</p>
              <p className="mt-1 text-sm text-cream-dim">{error}</p>
              <button
                type="button"
                onClick={generate}
                className="mt-3 text-xs uppercase tracking-[0.12em] text-accent hover:text-cream"
              >
                ✦ Retry
              </button>
            </div>
          ) : (
            <p className="whitespace-pre-wrap text-sm text-cream-dim">{result}</p>
          )}
          {!loading && !error && provider && (
            <p className="mt-2 text-[0.6rem] text-muted">Generated by {provider}</p>
          )}
          <p className="mt-3 text-[0.65rem] text-muted">Review before sending. AI never sends automatically.</p>
        </div>
      )}
    </div>
  );
}
