/**
 * Read the latest Admin OS audit report generated by `npm run audit:os`.
 * Used by Trust diagnostics (AI Ops / sign-off) — never invents findings.
 */

import { readFile } from "fs/promises";
import path from "path";

export interface AdminOsAuditSummary {
  generatedAt: string;
  gate: "PASS" | "FAIL" | "UNKNOWN";
  pages: number;
  working: number;
  partial: number;
  broken: number;
  findingsP0: number;
  findingsP1: number;
  findingsTotal: number;
  adminApisMissingAuth: number;
  liveProbes: string;
  recentFindings: { severity: string; title: string; category?: string }[];
}

type AuditJson = {
  generatedAt?: string;
  summary?: {
    pages?: number;
    working?: number;
    partial?: number;
    broken?: number;
    findingsP0?: number;
    findingsP1?: number;
    findingsTotal?: number;
    adminApisMissingAuth?: number;
    liveProbes?: string;
    gate?: string;
  };
  pages?: { status?: string }[];
  findings?: { severity?: string; title?: string; category?: string; id?: string }[];
  liveResults?: { ok?: boolean }[];
  inventory?: { osPages?: number; adminApiRoutes?: number };
};

export async function loadAdminOsAuditSummary(): Promise<AdminOsAuditSummary | null> {
  const file = path.join(process.cwd(), "docs/audits/admin-os-latest.json");
  try {
    const raw = await readFile(file, "utf8");
    const data = JSON.parse(raw) as AuditJson;
    const pages = Array.isArray(data.pages) ? data.pages : [];
    const findings = Array.isArray(data.findings) ? data.findings : [];
    const live = Array.isArray(data.liveResults) ? data.liveResults : [];

    const working = pages.filter((p) => p.status === "working").length;
    const partial = pages.filter((p) => p.status === "partial").length;
    const broken = pages.filter((p) => p.status === "broken").length;
    const p0 = findings.filter((f) => f.severity === "P0").length;
    const p1Blocking = findings.filter(
      (f) => f.severity === "P1" && f.id !== "live-probes-skipped"
    ).length;
    const liveProbes =
      live.length > 0
        ? `${live.filter((r) => r.ok).length}/${live.length} ok`
        : "skipped";

    const gateFromSummary = data.summary?.gate;
    const gate: AdminOsAuditSummary["gate"] =
      gateFromSummary === "PASS" || gateFromSummary === "FAIL"
        ? gateFromSummary
        : p0 === 0 && p1Blocking === 0
          ? "PASS"
          : "FAIL";

    return {
      generatedAt: data.generatedAt ?? "unknown",
      gate,
      pages: data.summary?.pages ?? data.inventory?.osPages ?? pages.length,
      working: data.summary?.working ?? working,
      partial: data.summary?.partial ?? partial,
      broken: data.summary?.broken ?? broken,
      findingsP0: data.summary?.findingsP0 ?? p0,
      findingsP1: data.summary?.findingsP1 ?? p1Blocking,
      findingsTotal: data.summary?.findingsTotal ?? findings.length,
      adminApisMissingAuth: data.summary?.adminApisMissingAuth ?? 0,
      liveProbes: data.summary?.liveProbes ?? liveProbes,
      recentFindings: findings.slice(0, 8).map((f) => ({
        severity: f.severity ?? "P3",
        title: f.title ?? "Finding",
        category: f.category,
      })),
    };
  } catch {
    return null;
  }
}
